### ISSUE TITLE
My env variables are not overrided by Azure App Settings ( System Env )

### ISSUE THREAD

**Issue by alamenai** [vorillaz/tutorials#1]
Hi @vorillaz .

Thank you for the nice article you published about Docker + NextJS. 

I'm following the relative [discussion ](https://github.com/vercel/next.js/discussions/17641) of the issue and I found that you shared a nice and clear solution for accessing the env variables in the runtime.

I applied all the steps you mentioned in your article but I still facing this issue:

1. I defined my env variable like this in `env.production`:

```
NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=
```

2. I created a system env variable in Azure App Settings:

![image](https://github.com/vorillaz/tutorials/assets/20143684/2bd9480c-1484-4f0d-ae10-c81f0c849629)

3. I implemented the function that access to this variable:

```ts
"use server"

export const getEnv = async () => ({
  NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN,
})

```

4. I called the function from a client component ( To check the output ):

```tsx
 useEffect(() => {
    getEnv().then((env) => {
      console.log(env) 
    })
  }, [])
```

After I deployed the app on Azure App Service, I'm still getting the initial value "" instead of the new one that's defined in the Env System ( App Settings ):

![image](https://github.com/vorillaz/tutorials/assets/20143684/78aa1bbc-2bf0-47f4-ae10-6b1aaceae293)

My `Dockerfile.prod`:

```Dockerfile
FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat


WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json ./

# You can use these package managers
# yarn.lock* package-lock.json* pnpm-lock.yaml*

# RUN \
#   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
#   elif [ -f package-lock.json ]; then npm ci; \
#   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
#   else echo "Lockfile not found." && exit 1; \
#   fi

RUN npm install --legacy-peer-deps --verbose

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
# set hostname to localhost
ENV HOSTNAME "0.0.0.0"
# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD ["node", "server.js"]
```

My `azure-pipelines.yml`

```yml
trigger:
  - credium-alpha

variables:
  dockerRegistryServiceConnection: "Hiden"
  imageRepository: "hidden"
  containerRegistry: "hidden.azurecr.io"
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile.prod"
  tag: "$(Build.BuildId)"
  vmImageName: "ubuntu-latest"

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Install
    displayName: "Install"
    jobs:
      - job: InstallJob
        displayName: "Install Node.js and Dependencies"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "20.x"
            displayName: "Install Node.js"
          - script: |
              npm install
            displayName: "Install Node.js and Dependencies"

  - stage: Tests
    displayName: "Run Unit and Component Tests"
    jobs:
      - job: TestsJob
        displayName: "Run Unit and Component Tests"
        steps:
          - script: |
              npm install
              npm test
              npm run cypress-run-component
            displayName: "Run Unit and Component Tests"

  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              buildContext: "./"
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

```
